name: Build Godot Project

on:
  release:
    types: [published]
  workflow_dispatch: {}

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

env:
  GODOT_VERSION: 3.5.1
  EXPORT_NAME: "blending-board-app"

jobs:
#   godot-build:
#     runs-on: ubuntu-latest
#     strategy:
#       matrix:
#         platform: [HTML5]
#     steps:
#       - uses: actions/checkout@v2
#         with:
#           lfs: true
# #       - name: Build
# #         id: build
# #         uses: josephbmanley/build-godot-action@v1.4.1
# #         with:
# #           name: Blendi
# #           preset: ${{ matrix.platform }}
# #           debugMode: "true"
#       - name: build
#         uses: abarichello/godot-ci@3.4.2
#       - name: Upload Artifact
#         uses: actions/upload-artifact@v2
#         with:
#           name: Client - ${{ matrix.platform }}
#           path: ${{ github.workspace }}/${{ steps.build.outputs.build }}
#       - name: Deploy to GitHub Pages
#         if: success()
#         uses: crazy-max/ghaction-github-pages@v3
#         with:
#           target_branch: gh-pages
#           build_dir: ${{ steps.build.outputs.build }}
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#       - name: Deploy
#         uses: peaceiris/actions-gh-pages@v3
#         with:
#           github_token: ${{ secrets.GITHUB_TOKEN }}
#           publish_dir: ${{ steps.build.outputs.build }}
  export-web:
    name: Web Export
    runs-on: ubuntu-20.04
    container:
      image: barichello/godot-ci:3.5.1
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Setup
        run: |
          mkdir -v -p build/linux build/windows build/mac build/web ~/.local/share/godot/templates
          mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable ~/.local/share/godot/templates/${GODOT_VERSION}.stable
      - name: Web Build
        run: godot -v --export "HTML5" ./build/web/index.html
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: web
          path: build/web
      - name: Install rsync 📚
        run: |
          apt-get update && apt-get install -y rsync
      - name: Deploy to GitHub Pages 🚀
        uses: JamesIves/github-pages-deploy-action@releases/v4
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: build/web # The folder the action should deploy.
